export const WORDS = [
    { word: "ABDOMEN", category: "Anatomía", description: "Región del cuerpo humano situada entre el tórax y la pelvis, que contiene la cavidad abdominal y los órganos del aparato digestivo y genitourinario." },
    { word: "ALVEOLO", category: "Anatomía", description: "Pequeño saco terminal del árbol bronquial donde tiene lugar la hematosis o intercambio de gases entre el aire y la sangre." },
    { word: "AMIGDALAS", category: "Anatomía", description: "Órganos de tejido linfático situados en la faringe que forman parte del sistema inmunitario, protegiendo contra infecciones de entrada bucal." },
    { word: "ANO", category: "Anatomía", description: "Orificio terminal del tubo digestivo a través del cual los materiales de desecho (heces) abandonan el organismo." },
    { word: "ANTEBRAZO", category: "Anatomía", description: "Segmento del miembro superior comprendido entre el codo y la muñeca, que contiene los huesos radio y cúbito." },
    { word: "ANULAR", category: "Anatomía", description: "Cuarto dedo de la mano humana, situado entre el dedo medio y el pequeño, tradicionalmente asociado al uso de anillos." },
    { word: "AORTA", category: "Anatomía", description: "La arteria más grande del cuerpo que nace del ventrículo izquierdo del corazón y distribuye la sangre oxigenada a todo el organismo." },
    { word: "APENDICE", category: "Anatomía", description: "Órgano pequeño de forma tubular unido al ciego, en el inicio del intestino grueso, cuya función exacta es objeto de debate científico." },
    { word: "AREOLA", category: "Anatomía", description: "Zona circular de piel pigmentada que rodea el pezón en la mama, que contiene glándulas sebáceas que lubrican la zona durante la lactancia." },
    { word: "ARTERIA", category: "Anatomía", description: "Vaso sanguíneo eferente que transporta sangre, generalmente oxigenada, desde el corazón hacia los diversos tejidos y órganos del cuerpo." },
    { word: "ARTICULACION", category: "Anatomía", description: "Estructura que une dos o más huesos, permitiendo o no el movimiento entre ellos y proporcionando estabilidad al esqueleto." },
    { word: "ATLAS", category: "Anatomía", description: "Nombre de la primera vértebra cervical (C1), que se articula con el cráneo y permite el movimiento de cabeceo de la cabeza." },
    { word: "AURICULAS", category: "Anatomía", description: "Cavidades superiores del corazón que reciben la sangre proveniente de las venas y la bombean hacia los ventrículos inferiores." },
    { word: "AXILAS", category: "Anatomía", description: "Zona del cuerpo situada debajo de la unión del brazo con el hombro, caracterizada por la presencia de ganglios linfáticos y glándulas sudoríparas." },
    { word: "AXON", category: "Anatomía", description: "Prolongación larga y única de la neurona que conduce el impulso nervioso desde el cuerpo celular hacia otra célula o tejido." },
    { word: "BARBILLA", category: "Anatomía", description: "Parte inferior de la cara situada por debajo del labio inferior, formada por la prominencia ósea del mentón en la mandíbula." },
    { word: "BARRIGA", category: "Anatomía", description: "Término coloquial para el abdomen, región que aloja el estómago y los intestinos." },
    { word: "BAZO", category: "Anatomía", description: "Órgano del sistema linfático que filtra la sangre, destruye glóbulos rojos viejos y ayuda a combatir infecciones como parte del sistema inmune." },
    { word: "BOCA", category: "Anatomía", description: "Abertura del tracto digestivo por la que se ingieren los alimentos, que además cumple funciones esenciales en el habla y la respiración." },
    { word: "BRAZO", category: "Anatomía", description: "En sentido estricto, es el segmento del miembro superior situado entre el hombro y el codo, cuyo único hueso es el húmero." },
    { word: "BRONQUIOS", category: "Anatomía", description: "Conductos tubulares en los que se bifurca la tráquea para penetrar en los pulmones, encargados de conducir el aire hacia los bronquiolos." },
    { word: "BRONQUIOLOS", category: "Anatomía", description: "Pequeñas ramificaciones de los bronquios, sin cartílago en su pared, que terminan en los racimos de alvéolos pulmonares." },
    { word: "CABELLO", category: "Anatomía", description: "Fibra de queratina que crece en el cuero cabelludo del ser humano, cuya función es proteger la cabeza de la radiación solar y el frío." },
    { word: "CABEZA", category: "Anatomía", description: "Parte superior del cuerpo de un animal o ser humano que contiene el encéfalo y los principales órganos sensoriales de la visión, oído, olfato y gusto." },
    { word: "CADERA", category: "Anatomía", description: "Articulación esferoidea que une el fémur con el hueso coxal de la pelvis, permitiendo una amplia gama de movimientos en la pierna." },
    { word: "CALCAÑAR", category: "Anatomía", description: "Parte posterior del pie formada por el hueso calcáneo, que constituye la estructura del talón y soporta gran parte del peso corporal." },
    { word: "CAPILAR", category: "Anatomía", description: "Vaso sanguíneo de diámetro microscópico cuyas paredes delgadas permiten el intercambio de nutrientes y gases entre la sangre y los tejidos." },
    { word: "CARA", category: "Anatomía", description: "Región anterior de la cabeza humana que abarca desde la frente hasta la barbilla y de oreja a oreja." },
    { word: "CARINATRAQUEAL", category: "Anatomía", description: "Cresta cartilaginosa situada en la base de la tráquea que separa las aberturas de los dos bronquios principales." },
    { word: "CAROTIDA", category: "Anatomía", description: "Cada una de las dos arterias principales del cuello que suministran sangre oxigenada de manera vital al cerebro y al rostro." },
    { word: "CEJA", category: "Anatomía", description: "Área prominente con vello situada sobre los ojos que protege el órgano visual del sudor, el polvo y el exceso de luz." },
    { word: "CEREBELO", category: "Anatomía", description: "Región del encéfalo situada en la parte posterior e inferior del cráneo encargada de coordinar el movimiento, el equilibrio y la postura." },
    { word: "CEREBRO", category: "Anatomía", description: "Parte más voluminosa del encéfalo que controla las funciones motoras, sensoriales y las capacidades cognitivas superiores como el lenguaje y la memoria." },
    { word: "CINTURA", category: "Anatomía", description: "Zona del tronco situada entre el tórax y las caderas, que por lo general es la parte más estrecha del abdomen." },
    { word: "CLAVICULA", category: "Anatomía", description: "Hueso largo y curvo situado en la parte superior e interna del tórax que conecta el brazo con el cuerpo." },
    { word: "CLITORIS", category: "Anatomía", description: "Pequeño órgano eréctil femenino, altamente inervado y sensible, cuya única función conocida es proporcionar placer sexual." },
    { word: "CODO", category: "Anatomía", description: "Articulación de bisagra que une el brazo con el antebrazo y permite la flexión y extensión del miembro superior." },
    { word: "COGOTE", category: "Anatomía", description: "Parte superior y posterior del cuello, también denominada nuca, donde la cabeza se une a la columna cervical." },
    { word: "COLMILLO", category: "Anatomía", description: "Nombre común del diente canino, caracterizado por su forma puntiaguda diseñada para desgarrar los alimentos." },
    { word: "COLON", category: "Anatomía", description: "Segmento más largo del intestino grueso cuya función principal es la absorción de agua y la formación de heces antes de la excreción." },
    { word: "COLUMNAVERTEBRAL", category: "Anatomía", description: "Estructura ósea articulada que se extiende desde el cráneo hasta la pelvis, que protege la médula espinal y sostiene el eje del cuerpo." },
    { word: "CONDILO", category: "Anatomía", description: "Eminencia redondeada en el extremo de un hueso que se articula en el hueco de otro hueso para formar una articulación móvil." },
    { word: "CORAZON", category: "Anatomía", description: "Órgano muscular hueco que funciona como una bomba aspirante e impelente, impulsando la sangre por todo el sistema circulatorio." },
    { word: "CORVA", category: "Anatomía", description: "Zona del cuerpo situada detrás de la rodilla, donde se flexionan los tendones de los músculos del muslo." },
    { word: "COSTILLA", category: "Anatomía", description: "Hueso largo, elástico y curvo que se articula con la columna vertebral y el esternón formando la caja torácica protectora." },
    { word: "COXIS", category: "Anatomía", description: "Último hueso pequeño de la columna vertebral, de forma triangular, que representa el vestigio de una cola en los ancestros humanos." },
    { word: "CRANEO", category: "Anatomía", description: "Caja ósea que rodea y protege el encéfalo, formada por los huesos frontales, parietales, temporales, occipital, esfenoides y etmoides." },
    { word: "CUBITO", category: "Anatomía", description: "Hueso largo del antebrazo, situado paralelamente al radio pero en el lado interno (lado del dedo meñique)." },
    { word: "CUELLO", category: "Anatomía", description: "Segmento del cuerpo que conecta la cabeza con el tórax y que contiene estructuras vitales como la tráquea, el esófago y la tiroides." },
    { word: "CUERPO", category: "Anatomía", description: "Estructura física y orgánica que constituye el organismo humano en su totalidad." },
    { word: "CULO", category: "Anatomía", description: "Término vulgar para denominar a los glúteos, las nalgas o la región posterior de la pelvis." },
    { word: "CUTICULA", category: "Anatomía", description: "Capa protectora de piel muerta que bordea la base de las uñas de las manos y de los pies." },
    { word: "DEDO", category: "Anatomía", description: "Cada una de las extremidades articuladas que terminan las manos y los pies, esenciales para la manipulación y la locomoción." },
    { word: "DELTOIDES", category: "Anatomía", description: "Músculo de forma triangular que recubre la articulación del hombro y es responsable de levantar el brazo lateralmente." },
    { word: "DIAFRAGMA", category: "Anatomía", description: "Músculo plano y ancho que separa la cavidad torácica de la abdominal y es el principal motor de la respiración." },
    { word: "DIENTES", category: "Anatomía", description: "Órganos anatómicos duros, enclavados en los maxilares, encargados de la fragmentación de los alimentos durante la masticación." },
    { word: "DUODENO", category: "Anatomía", description: "Primera de las tres partes del intestino delgado que conecta el estómago con el yeyuno, recibiendo la bilis y el jugo pancreático." },
    { word: "ENCEFALO", category: "Anatomía", description: "Cerebro, cerebelo y tronco encefálico contenidos dentro del cráneo, constituyendo el centro de control de todo el sistema nervioso." },
    { word: "ENCIA", category: "Anatomía", description: "Tejido mucoso y fibroso que rodea la base de los dientes y recubre el hueso maxilar dentro de la boca." },
    { word: "ENTRECEJO", category: "Anatomía", description: "Espacio rugoso de la frente situado entre las dos cejas, justo encima de la raíz de la nariz." },
    { word: "EPIDIDIMO", category: "Anatomía", description: "Conducto estrecho y alargado situado detrás de cada testículo donde se almacenan y maduran los espermatozoides." },
    { word: "ESCAPULA", category: "Anatomía", description: "Hueso plano, grande y triangular situado en la parte posterior del hombro, también conocido como omóplato." },
    { word: "ESCROTO", category: "Anatomía", description: "Bolsa de piel que contiene y protege los testículos, manteniéndolos a una temperatura inferior a la del resto del cuerpo para la producción de esperma." },
    { word: "ESFINTER", category: "Anatomía", description: "Músculo en forma de anillo que cierra y abre un orificio natural del cuerpo para controlar el paso de sustancias." },
    { word: "ESOFAGO", category: "Anatomía", description: "Conducto muscular que transporta el bolo alimenticio desde la faringe hasta el estómago mediante movimientos peristálticos." },
    { word: "ESPALDA", category: "Anatomía", description: "Parte posterior del cuerpo humano que va desde la base del cuello hasta los glúteos." },
    { word: "ESQUELETO", category: "Anatomía", description: "Sistema biológico de soporte que proporciona la estructura corporal y protege los órganos internos, formado por 206 huesos." },
    { word: "ESTERNOCLEIDOMASTOIDEO", category: "Anatomía", description: "Músculo robusto del cuello que permite la rotación de la cabeza hacia el lado opuesto y su inclinación lateral." },
    { word: "ESTERNON", category: "Anatomía", description: "Hueso plano situado en la parte media y anterior del tórax al que se unen las costillas verdaderas." },
    { word: "ESTOMAGO", category: "Anatomía", description: "Órgano muscular en forma de saco donde se inicia la digestión química de las proteínas mediante los jugos gástricos." },
    { word: "ESFENOIDES", category: "Anatomía", description: "Hueso de forma compleja parecido a una mariposa situado en la base del cráneo, detrás de los ojos." },
    { word: "ETMOIDES", category: "Anatomía", description: "Hueso ligero y esponjoso situado delante del esfenoides que contribuye a formar la cavidad nasal y las órbitas oculares." },
    { word: "EXTREMIDAD", category: "Anatomía", description: "Miembro articulado que sobresale del tronco de un animal o ser humano destinado al movimiento o manipulación." },
    { word: "FALANGE", category: "Anatomía", description: "Hueso corto que forma el esqueleto de los dedos de las manos y de los pies." },
    { word: "FARINGE", category: "Anatomía", description: "Conducto de paredes musculosas que conecta la boca y la nariz con el esófago y la laringe, sirviendo al paso de aire y alimentos." },
    { word: "FOSANASAL", category: "Anatomía", description: "Cavidad situada en el interior de la nariz cuya función es filtrar, calentar y humedecer el aire inhalado." },
    { word: "FEMUR", category: "Anatomía", description: "Hueso del muslo que se extiende desde la cadera hasta la rodilla, siendo el más largo y fuerte del cuerpo humano." },
    { word: "FRENTE", category: "Anatomía", description: "Zona de la cara comprendida entre el nacimiento del cabello y las cejas, centrada sobre el hueso frontal." },
    { word: "FORAMENOVAL", category: "Anatomía", description: "Abertura fisiológica en el corazón fetal que permite el paso de sangre entre las dos aurículas antes del nacimiento." },
    { word: "GANGLIO", category: "Anatomía", description: "Acúmulo de células nerviosas o de tejido linfático que actúa como estación de relevo o filtro en el cuerpo." },
    { word: "GLANDE", category: "Anatomía", description: "Parte final y sensible del pene en el hombre o del clítoris en la mujer, ricamente inervada para la respuesta sexual." },
    { word: "GLANDULASDEKRAUSE", category: "Anatomía", description: "Glándulas lagrimales microscópicas accesorias situadas bajo la conjuntiva del ojo que contribuyen a mantener la lubricación ocular." },
    { word: "GLOTIS", category: "Anatomía", description: "Espacio o abertura de la laringe limitado por las cuerdas vocales, esencial para la fonación y la respiración." },
    { word: "GLUTEO", category: "Anatomía", description: "Cualquiera de los tres músculos que forman las nalgas, fundamentales para caminar y mantener la postura erguida." },
    { word: "GONADA", category: "Anatomía", description: "Órgano reproductor animal que produce los gametos (testículo en los machos y ovario en las hembras)." },
    { word: "GARGANTA", category: "Anatomía", description: "Parte anterior del cuello situada delante de la columna vertebral que contiene la faringe y la laringe." },
    { word: "HELICE", category: "Anatomía", description: "Borde curvo y prominente que forma el contorno exterior del pabellón de la oreja." },
    { word: "HIGADO", category: "Anatomía", description: "Glándula de gran tamaño que produce bilis, almacena energía y purifica la sangre eliminando toxinas." },
    { word: "HIOIDES", category: "Anatomía", description: "Hueso único en forma de U situado en el cuello, justo debajo de la lengua, que no se articula con ningún otro hueso." },
    { word: "HIPOFISIS", category: "Anatomía", description: "Glándula endocrina maestra situada en la base del cerebro que controla la mayoría de los procesos hormonales del cuerpo." },
    { word: "HIPOTALAMO", category: "Anatomía", description: "Región del cerebro que regula la temperatura corporal, el hambre, la sed y los ritmos biológicos, conectando el sistema nervioso con el endocrino." },
    { word: "HOMBRO", category: "Anatomía", description: "Articulación compleja que une el brazo con el tronco, permitiendo el mayor grado de libertad de movimiento del cuerpo." },
    { word: "HUESOS", category: "Anatomía", description: "Órganos anatómicos rígidos y blanquecinos que forman el endoesqueleto de los vertebrados, proporcionando soporte y protección." },
    { word: "HUMERO", category: "Anatomía", description: "Hueso largo que constituye el esqueleto del brazo, articulándose con la escápula y con los huesos del antebrazo." },
    { word: "INDICE", category: "Anatomía", description: "Segundo dedo de la mano, situado entre el pulgar y el dedo medio, comúnmente utilizado para señalar." },
    { word: "INGLE", category: "Anatomía", description: "Pliegue o depresión que marca la unión de la parte inferior del abdomen con el muslo." },
    { word: "ILEON", category: "Anatomía", description: "Tercera y última porción del intestino delgado encargada de absorber la vitamina B12 y las sales biliares." },
    { word: "INTESTINOGRUESO", category: "Anatomía", description: "Parte final del sistema digestivo que absorbe agua del material no digerido y lo prepara para su eliminación." },
    { word: "INTESTINODELGADO", category: "Anatomía", description: "Órgano tubular de unos 6 a 7 metros de longitud donde ocurre la mayor parte de la digestión y la absorción de nutrientes." },
    { word: "IRIS", category: "Anatomía", description: "Membrana coloreada y circular del ojo con una abertura central que regula la cantidad de luz que entra en el órgano visual." },
    { word: "JOROBA", category: "Anatomía", description: "Curvatura anormal de la columna vertebral que provoca una protuberancia en la espalda, técnicamente conocida como cifosis." },
    { word: "JUANETE", category: "Anatomía", description: "Deformación de la articulación del dedo gordo del pie que causa que este se incline hacia los demás dedos." },
    { word: "JUNTURA", category: "Anatomía", description: "Término anatómico para designar la unión o articulación entre dos o más huesos." },
    { word: "LABIOS", category: "Anatomía", description: "Pliegues musculares y mucosos que delimitan la entrada de la boca y participan en la alimentación y el habla." },
    { word: "LAGRIMAL", category: "Anatomía", description: "Cada uno de los dos pequeños huesos planos de la cara que contienen el conducto por donde pasan las lágrimas." },
    { word: "LARINGE", category: "Anatomía", description: "Órgano tubular encargado de la producción de la voz que impide que los alimentos pasen a las vías respiratorias durante la deglución." },
    { word: "LENGUA", category: "Anatomía", description: "Órgano muscular muy móvil situado en la boca, encargado del gusto, la succión, la deglución y el lenguaje articulado." },
    { word: "LOBULO", category: "Anatomía", description: "Parte redondeada de un órgano, como el lóbulo de la oreja, el lóbulo pulmonar o el lóbulo cerebral." },
    { word: "LOMO", category: "Anatomía", description: "Parte inferior de la espalda a ambos lados de la columna vertebral, entre las costillas y las caderas." },
    { word: "MACULA", category: "Anatomía", description: "Zona pequeña y amarillenta de la retina del ojo responsable de la visión central, la agudeza visual y la percepción de los colores." },
    { word: "MALEOLO", category: "Anatomía", description: "Protuberancia ósea que forma la parte inferior de la tibia o del peroné en la zona del tobillo." },
    { word: "MAMA", category: "Anatomía", description: "Órgano glandular externo de los mamíferos encargado de producir leche para nutrir a las crías." },
    { word: "MANO", category: "Anatomía", description: "Parte extrema de cada uno de los brazos del ser humano, dotada de cinco dedos y gran capacidad de prensión." },
    { word: "MANDIBULA", category: "Anatomía", description: "Hueso impar y móvil de la cara que constituye la base de la boca y contiene los dientes inferiores." },
    { word: "MARTILLO", category: "Anatomía", description: "Huesecillo más externo del oído medio que transmite las vibraciones sonoras desde el tímpano hasta el yunque." },
    { word: "MAXILARES", category: "Anatomía", description: "Huesos que forman las mandíbulas superior e inferior, proporcionando estructura a la boca y anclaje a las piezas dentales." },
    { word: "MEDIO", category: "Anatomía", description: "Tercer dedo de la mano humana, también llamado dedo corazón, situado entre el índice y el anular." },
    { word: "MEJILLA", category: "Anatomía", description: "Cada una de las dos partes carnosas de la cara humana situadas por debajo de los ojos y a los lados de la nariz." },
    { word: "MENINGES", category: "Anatomía", description: "Cada una de las tres membranas (duramadre, aracnoides y piamadre) que envuelven y protegen el encéfalo y la médula espinal." },
    { word: "MENISCOS", category: "Anatomía", description: "Cartílagos de forma semilunar situados en la articulación de la rodilla que actúan como amortiguadores." },
    { word: "MENTON", category: "Anatomía", description: "Prominencia ósea situada en la parte central e inferior de la mandíbula que define la barbilla humana." },
    { word: "MEÑIQUE", category: "Anatomía", description: "Dedo más pequeño y extremo de la mano o del pie, correspondiente al quinto dígito." },
    { word: "METACARPO", category: "Anatomía", description: "Conjunto de cinco huesos largos que forman la estructura interna de la palma de la mano." },
    { word: "METATARSO", category: "Anatomía", description: "Conjunto de cinco huesos largos del pie situados entre el tarso y las falanges de los dedos." },
    { word: "MUELA", category: "Anatomía", description: "Cada uno de los dientes posteriores cuya corona ancha permite triturar eficazmente los alimentos." },
    { word: "MUÑECA", category: "Anatomía", description: "Articulación compleja que une los huesos del antebrazo con los del carpo, permitiendo diversos movimientos de la mano." },
    { word: "MUSCULO", category: "Anatomía", description: "Tejido compuesto por fibras contráctiles que genera fuerza y movimiento en el cuerpo humano." },
    { word: "MUSLO", category: "Anatomía", description: "Primer segmento de la pierna comprendido entre la cadera y la rodilla, cuyo único hueso es el fémur." },
    { word: "NALGA", category: "Anatomía", description: "Cada una de las dos partes carnosas y redondeadas de la zona posterior de la pelvis, formadas principalmente por los músculos glúteos." },
    { word: "NARINA", category: "Anatomía", description: "Cada uno de los dos orificios externos de la nariz que permiten el paso del aire hacia las fosas nasales." },
    { word: "NARIZ", category: "Anatomía", description: "Órgano de la cara que contiene las vías olfatorias y actúa como el principal conducto del aire respirado." },
    { word: "NEFRON", category: "Anatomía", description: "Unidad anatómica y funcional del riñón, responsable de filtrar la sangre para formar la orina." },
    { word: "NEURONA", category: "Anatomía", description: "Célula especializada del sistema nervioso cuya función consiste en transmitir información mediante impulsos eléctricos y químicos." },
    { word: "NUCA", category: "Anatomía", description: "Parte superior y posterior del cuello en la zona de unión de este con el cráneo." },
    { word: "NUEZ", category: "Anatomía", description: "Prominencia en la parte anterior del cuello producida por el cartílago tiroides, más visible en los hombres." },
    { word: "OCCIPITAL", category: "Anatomía", description: "Hueso que forma la parte posterior e inferior del cráneo y presenta el orificio por donde pasa la médula espinal." },
    { word: "OIDO", category: "Anatomía", description: "Órgano complejo responsable de la audición y del mantenimiento del equilibrio en el espacio." },
    { word: "OJO", category: "Anatomía", description: "Órgano fotorreceptor complejo que capta la luz y la transforma en señales nerviosas para el cerebro." },
    { word: "OMBLIGO", category: "Anatomía", description: "Cicatriz en el centro del abdomen producida tras la caída del cordón umbilical en los mamíferos placentarios." },
    { word: "OREJA", category: "Anatomía", description: "Estructura externa del aparato auditivo, formada por cartílago recubierto de piel, que recoge los sonidos." },
    { word: "OMOPLATO", category: "Anatomía", description: "Nombre común de la escápula, hueso plano situado en la parte superior y posterior del tórax." },
    { word: "OVULO", category: "Anatomía", description: "Célula reproductora o gameto femenino que, al ser fecundada por un espermatozoide, da origen al cigoto." },
    { word: "OVARIO", category: "Anatomía", description: "Órgano reproductor femenino encargado de la producción de óvulos y de la secreción de hormonas sexuales." },
    { word: "OCCIPUCIO", category: "Anatomía", description: "Región anatómica situada en la parte posteroinferior de la cabeza." },
    { word: "PANCREAS", category: "Anatomía", description: "Glándula mixta situada detrás del estómago que produce enzimas digestivas y hormonas como la insulina." },
    { word: "PANTORRILLA", category: "Anatomía", description: "Parte posterior e inferior de la pierna, formada fundamentalmente por los músculos gemelos y el sóleo." },
    { word: "PARPADO", category: "Anatomía", description: "Pliegue de piel móvil que protege el globo ocular y ayuda a mantenerlo húmedo mediante el parpadeo." },
    { word: "PECHO", category: "Anatomía", description: "Parte anterior del tórax situada entre el cuello y el abdomen." },
    { word: "PELO", category: "Anatomía", description: "Producción de la piel en forma de filamento delgado y flexible compuesto principalmente por queratina." },
    { word: "PENE", category: "Anatomía", description: "Órgano copulador masculino encargado también de la expulsión de la orina al exterior." },
    { word: "PERONE", category: "Anatomía", description: "Hueso largo y delgado de la pierna, paralelo a la tibia, que actúa principalmente como punto de anclaje para los músculos." },
    { word: "PESTAÑA", category: "Anatomía", description: "Cada uno de los pelos que crecen en el borde del párpado y cuya función es evitar la entrada de suciedad en el ojo." },
    { word: "PEZON", category: "Anatomía", description: "Pequeña protuberancia en el centro de la mama por donde sale la leche en las hembras lactantes." },
    { word: "PIEL", category: "Anatomía", description: "Órgano más extenso del cuerpo humano que actúa como barrera protectora frente al medio ambiente." },
    { word: "PIERNA", category: "Anatomía", description: "En sentido estricto, es el segmento del miembro inferior situado entre la rodilla y el tobillo." },
    { word: "PIE", category: "Anatomía", description: "Parte terminal del miembro inferior que sostiene el peso del cuerpo y permite la bipedestación y la marcha." },
    { word: "PLEURAS", category: "Anatomía", description: "Finas membranas serosas que envuelven los pulmones y recubren el interior de la cavidad torácica." },
    { word: "POMULO", category: "Anatomía", description: "Hueso cigomático de la cara que sobresale debajo de la cuenca del ojo." },
    { word: "PREPUCIO", category: "Anatomía", description: "Pliegue mucocutáneo de piel móvil que cubre y protege el glande del pene." },
    { word: "PUBIS", category: "Anatomía", description: "Región delantera de la pelvis situada encima de los genitales externos y recubierta de vello en la madurez." },
    { word: "PULMON", category: "Anatomía", description: "Órgano principal del sistema respiratorio donde se realiza el intercambio gaseoso vital para la vida." },
    { word: "PUPILA", category: "Anatomía", description: "Abertura circular situada en el centro del iris a través de la cual la luz penetra en el globo ocular." },
    { word: "PARATIROIDES", category: "Anatomía", description: "Cada una de las cuatro pequeñas glándulas situadas detrás de la tiroides que regulan los niveles de calcio en sangre." },
    { word: "PULGAR", category: "Anatomía", description: "Primer dedo de la mano, caracterizado por ser oponible a los demás, lo que permite realizar la pinza y manipular objetos con precisión." },
    { word: "QUIMO", category: "Anatomía", description: "Masa semisólida y ácida formada por los alimentos parcialmente digeridos que pasa del estómago al duodeno." },
    { word: "QUISTE", category: "Anatomía", description: "Cavidad o saco cerrado que contiene material líquido, semisólido o gaseoso y que puede aparecer en diversas partes del cuerpo." },
    { word: "QUIJADA", category: "Anatomía", description: "Nombre común de la mandíbula o de los maxilares en su conjunto." },
    { word: "RADIO", category: "Anatomía", description: "Hueso largo del antebrazo, situado en el lado externo (lado del pulgar) y que se articula con el húmero y los huesos del carpo." },
    { word: "RECTO", category: "Anatomía", description: "Última porción del intestino grueso que almacena las heces hasta el momento de la defecación." },
    { word: "RIÑON", category: "Anatomía", description: "Órgano par que filtra la sangre para eliminar desechos y regular el equilibrio de agua y sales en el organismo." },
    { word: "RODILLA", category: "Anatomía", description: "Articulación que une el muslo con la pierna y permite la flexión y extensión de la extremidad inferior." },
    { word: "ROSTRO", category: "Anatomía", description: "Sinónimo de cara, región frontal de la cabeza que expresa las emociones y la identidad de la persona." },
    { word: "ROTULA", category: "Anatomía", description: "Hueso sesamoideo, pequeño y plano, situado en la parte anterior de la rodilla que mejora la eficacia del músculo cuádriceps." },
    { word: "SACRO", category: "Anatomía", description: "Hueso de forma triangular formado por la unión de cinco vértebras fusionadas en la base de la columna vertebral." },
    { word: "SANGRE", category: "Anatomía", description: "Tejido conectivo líquido que circula por los vasos sanguíneos transportando oxígeno, nutrientes y hormonas a las células." },
    { word: "SANGRIA", category: "Anatomía", description: "Parte del cuerpo humano opuesta al codo, donde frecuentemente se realizan extracciones de sangre." },
    { word: "SENO", category: "Anatomía", description: "Cavidad en un hueso o pliegue en un órgano, término también utilizado para referirse a la mama femenina." },
    { word: "SESO", category: "Anatomía", description: "Masa de tejido nervioso contenida en el interior del cráneo; término coloquial para el cerebro." },
    { word: "SIEN", category: "Anatomía", description: "Zona lateral de la cabeza comprendida entre la frente, la oreja y la parte superior de la mejilla." },
    { word: "SILLATURCA", category: "Anatomía", description: "Hueco profundo situado en el hueso esfenoides del cráneo que aloja y protege a la glándula hipófisis." },
    { word: "SOBACO", category: "Anatomía", description: "Término común para designar la axila, zona hueca debajo del hombro." },
    { word: "TABIQUENASAL", category: "Anatomía", description: "Estructura central de hueso y cartílago que separa las dos fosas nasales." },
    { word: "TALON", category: "Anatomía", description: "Extremo posterior del pie humano formado por el hueso calcáneo." },
    { word: "TARSO", category: "Anatomía", description: "Conjunto de siete huesos que forman la parte posterior del pie y lo conectan con la pierna." },
    { word: "TEJIDO", category: "Anatomía", description: "Conjunto organizado de células con características y funciones comunes dentro de un organismo." },
    { word: "TESTICULO", category: "Anatomía", description: "Glándula reproductora masculina encargada de producir espermatozoides y hormonas como la testosterona." },
    { word: "TETILLA", category: "Anatomía", description: "Pezón pequeño y rudimentario que presentan los individuos del sexo masculino." },
    { word: "TIBIA", category: "Anatomía", description: "Hueso principal, grueso e interno de la pierna que soporta la mayor parte del peso corporal del individuo." },
    { word: "TIMPANO", category: "Anatomía", description: "Delgada membrana elástica que separa el oído externo del medio y vibra al recibir ondas sonoras." },
    { word: "TIROIDES", category: "Anatomía", description: "Glándula endocrina en forma de mariposa situada en el cuello que regula el metabolismo del organismo." },
    { word: "TOBILLO", category: "Anatomía", description: "Articulación que conecta la pierna con el pie y permite la locomoción." },
    { word: "TORAX", category: "Anatomía", description: "Región del cuerpo humano comprendida entre la base del cuello y el diafragma, también llamada pecho." },
    { word: "TORSO", category: "Anatomía", description: "Tronco del cuerpo humano, prescindiendo de la cabeza y de las extremidades." },
    { word: "TRAPECIO", category: "Anatomía", description: "Músculo grande y plano situado en la parte superior del dorso que ayuda al movimiento de los hombros y el cuello." },
    { word: "TRAQUEA", category: "Anatomía", description: "Conducto respiratorio rígido y cartilaginoso que lleva el aire desde la laringe hacia los pulmones." },
    { word: "TRIGEMINO", category: "Anatomía", description: "Quinto par craneal, responsable de la sensibilidad facial y de la función motora de los músculos masticadores." },
    { word: "TRONCO", category: "Anatomía", description: "Parte central del organismo humano que incluye el tórax, el abdomen y la pelvis." },
    { word: "TIMO", category: "Anatomía", description: "Órgano linfoide primario situado detrás del esternón donde maduran las células T del sistema inmunitario." },
    { word: "TROMPADEFALOPIO", category: "Anatomía", description: "Conducto muscular que conecta el ovario con el útero y es el lugar habitual de la fecundación." },
    { word: "ULNA", category: "Anatomía", description: "Término anatómico para designar al hueso cúbito del antebrazo." },
    { word: "URETER", category: "Anatomía", description: "Conducto muscular largo que transporta la orina desde la pelvis renal hasta la vejiga urinaria." },
    { word: "URETRA", category: "Anatomía", description: "Conducto final del sistema urinario por el cual se expulsa la orina al exterior desde la vejiga." },
    { word: "UÑA", category: "Anatomía", description: "Lámina córnea y dura de queratina que protege la punta de los dedos de manos y pies." },
    { word: "UVULA", category: "Anatomía", description: "Pequeño apéndice carnoso que cuelga al final del velo del paladar, comúnmente llamada campanilla." },
    { word: "UTERO", category: "Anatomía", description: "Órgano muscular hueco femenino en el cual se implanta y desarrolla el embrión y feto durante el embarazo." },
    { word: "VAGINA", category: "Anatomía", description: "Conducto elástico y musculoso que comunica el útero con el exterior del cuerpo femenino." },
    { word: "VEJIGA", category: "Anatomía", description: "Órgano hueco de paredes musculosas encargado de almacenar la orina de forma temporal." },
    { word: "VELLO", category: "Anatomía", description: "Pelo corto y suave que cubre algunas zonas del cuerpo humano que no tienen vello terminal." },
    { word: "VENA", category: "Anatomía", description: "Vaso sanguíneo que conduce la sangre desde los capilares de retorno hacia el corazón." },
    { word: "VERTEBRA", category: "Anatomía", description: "Cada uno de los huesos cortos que componen la columna vertebral y protegen la médula espinal." },
    { word: "VESICULABILIAR", category: "Anatomía", description: "Órgano pequeño en forma de pera que almacena y concentra la bilis necesaria para digerir las grasas." },
    { word: "VESICULASEMINAL", category: "Anatomía", description: "Cada una de las dos glándulas masculinas que secretan gran parte del volumen líquido del semen." },
    { word: "VIENTRE", category: "Anatomía", description: "Región del cuerpo humano que comprende la cavidad abdominal." },
    { word: "VOMER", category: "Anatomía", description: "Hueso delgado y plano que forma la parte posterior del tabique nasal." },
    { word: "VULVA", category: "Anatomía", description: "Conjunto de los órganos genitales externos de la mujer." },
    { word: "XIFOIDES", category: "Anatomía", description: "Porción más pequeña e inferior del esternón, de naturaleza cartilaginosa al nacer." },
    { word: "YEMA", category: "Anatomía", description: "Extremo distal, carnoso e hipersensible de los dedos de la mano." },
    { word: "YEYUNO", category: "Anatomía", description: "Parte media del intestino delgado situada entre el duodeno y el íleon." },
    { word: "YUGULAR", category: "Anatomía", description: "Cualquiera de las varias venas del cuello que devuelven la sangre de la cabeza al corazón." },
    { word: "YUNQUE", category: "Anatomía", description: "Huesecillo del oído medio cuya vibración se transmite desde el martillo hacia el estribo." },
    { word: "ZANCAJO", category: "Anatomía", description: "Parte posterior del pie donde se encuentra el talón; hueso calcáneo." }
];
