export const WORDS = [
    // Original list
    { word: "ISCAR", category: "Nombre de la villa", description: "Corazón de la Tierra de Pinares." },
    { word: "TORRE", category: "Castillo", description: "Elemento central del castillo de Íscar." },
    { word: "PINOS", category: "Entorno natural", description: "Entorno natural de la comarca." },
    { word: "DANZA", category: "Cultura", description: "Legado de la bailarina Mariemma." },
    { word: "RUEDO", category: "Tradición", description: "Tradición taurina y plaza de toros." },
    { word: "ARTES", category: "Industria", description: "Artesanía local y ebanistería." },
    { word: "RESIN", category: "Industria", description: "Histórica industria de la resina." },
    { word: "MADERA", category: "Economía", description: "Motor económico de la localidad." },
    { word: "MUEBLE", category: "Industria", description: "Producto principal de su industria." },
    { word: "ERMITA", category: "Religión", description: "Cristo Rey o el Humilladero." },
    { word: "ENCINA", category: "Naturaleza", description: "Flora característica de la zona." },
    { word: "QUINTO", category: "Tradición", description: "Tradición de los jóvenes locales." },
    { word: "CASTILLO", category: "Patrimonio", description: "Fortaleza defensiva medieval." },
    { word: "MARIEMMA", category: "Cultura", description: "Figura ilustre de la danza española." },
    { word: "PIÑONES", category: "Gastronomía", description: "Fruto de los pinos albares." },
    { word: "ENCIERRO", category: "Eventos", description: "Evento clave de las fiestas de agosto." },
    { word: "PARAMO", category: "Geografía", description: "Geografía que rodea el municipio." },
    { word: "EBANISTA", category: "Oficio", description: "Oficio tradicional iscariense." },
    { word: "SERRERIA", category: "Industria", description: "Industria de transformación primaria." },
    { word: "CUERDEAS", category: "Festividad", description: "Festividad de la Virgen de los Mártires." },
    { word: "POLIGONO", category: "Empresa", description: "Zona de concentración empresarial." },
    { word: "FESTEJOS", category: "Cultura", description: "Cultura y eventos populares." },
    { word: "CASTELLUM", category: "Cultura", description: "Espacio cultural en el castillo." },
    { word: "HUMILLADERO", category: "Monumento", description: "Monumento religioso de entrada." },
    
    // New additions
    { word: "FERIA", category: "Eventos", description: "Eventos comerciales y festivos locales." },
    { word: "LUCIO", category: "Empresa", description: "Referencia a la empresa de autocares local." },
    { word: "PEÑAS", category: "Cultura", description: "Agrupaciones clave en las fiestas de la villa." },
    { word: "VALLA", category: "Eventos", description: "En alusión al cerramiento de los tradicionales encierros." },
    { word: "SANTO", category: "Patrimonio", description: "Por San Miguel, patrón de la Villa de Íscar." },
    { word: "BRAVO", category: "Tradición", description: "Referencia al ganado de las capeas e ímpetu local." },
    { word: "PIRATA", category: "Cultura", description: "Nombre de la conocida discoteca y sala de eventos." },
    { word: "PUENTE", category: "Geografía", description: "Infraestructuras sobre el río Pirón." },
    { word: "MARTIR", category: "Religión", description: "Por la devoción a la Virgen de los Mártires." },
    { word: "MOZOS", category: "Cultura", description: "Protagonistas de las fiestas, quintos y jotas." },
    { word: "CUESTA", category: "Geografía", description: "La subida característica que lleva al castillo." },
    { word: "ALBARIN", category: "Naturaleza", description: "Variedad de pino de la zona de pinares." },
    { word: "CARLOTA", category: "Empresa", description: "Referencia a la conocida marca Carlota&co." },
    { word: "FRONTON", category: "Deporte", description: "Deporte de pelota con mucha afición en el pueblo." },
    { word: "ESTATUA", category: "Patrimonio", description: "Monumento a Mariemma situado en el centro." },
    { word: "ISCARAS", category: "Cultura", description: "Gentilicio femenino de las habitantes de la villa." },
    { word: "PINARES", category: "Geografía", description: "Comarca natural a la que pertenece el municipio." },
    { word: "MADERAS", category: "Industria", description: "Apellido industrial de muchas familias iscarienses." },
    { word: "TAURINO", category: "Cultura", description: "Arraigo de la cultura del toro en Íscar." },
    { word: "PAJARES", category: "Geografía", description: "Paraje o zona de campo local del municipio." },
    { word: "RESINEROS", category: "Oficio", description: "Oficio histórico del monte y la resina." },
    { word: "ARTESANIA", category: "Industria", description: "Valor diferencial del mueble de Íscar." },
    { word: "PARROQUIA", category: "Religión", description: "Iglesia de Santa María o San Miguel." },
    { word: "INDUSTRIAL", category: "Economía", description: "Carácter principal del pujante municipio." },
    { word: "ISCARIENSES", category: "Cultura", description: "Gentilicio oficial de los habitantes de Íscar." }
];
